/*
   Este arquivo faz parte da JCFLIGHT.

   JCFLIGHT é um software livre: você pode redistribuí-lo e/ou modificar
   sob os termos da GNU General Public License conforme publicada por
   a Free Software Foundation, seja a versão 3 da Licença, ou
   (à sua escolha) qualquer versão posterior.

  JCFLIGHT é distribuído na esperança de ser útil,
  mas SEM QUALQUER GARANTIA; sem mesmo a garantia implícita de
  COMERCIALIZAÇÃO ou ADEQUAÇÃO A UM DETERMINADO FIM. Veja o
  GNU General Public License para mais detalhes.

   Você deve ter recebido uma cópia da Licença Pública Geral GNU
  junto com a JCFLIGHT. Caso contrário, consulte <http://www.gnu.org/licenses/>.
*/

#include "PIDPARAMS.h"
#include "StorageManager/EEPROMSTORAGE.h"
#include "BAR/BAR.h"
#include "Common/ENUM.h"
#include "GPSNavigation/NAVIGATION.h"

PID_Terms_Struct GET_SET[SIZE_OF_PID_PARAMS];

void Load_All_PID_Params(void)
{
    GET_SET[PID_ROLL].kP = STORAGEMANAGER.Read_8Bits(KP_ROLL_ADDR);
    GET_SET[PID_ROLL].kI = STORAGEMANAGER.Read_8Bits(KI_ROLL_ADDR);
    GET_SET[PID_ROLL].kD = STORAGEMANAGER.Read_8Bits(KD_ROLL_ADDR);
    GET_SET[PID_ROLL].kFF = STORAGEMANAGER.Read_8Bits(FF_OR_CD_ROLL_ADDR);

    GET_SET[PID_PITCH].kP = STORAGEMANAGER.Read_8Bits(KP_PITCH_ADDR);
    GET_SET[PID_PITCH].kI = STORAGEMANAGER.Read_8Bits(KI_PITCH_ADDR);
    GET_SET[PID_PITCH].kD = STORAGEMANAGER.Read_8Bits(KD_PITCH_ADDR);
    GET_SET[PID_PITCH].kFF = STORAGEMANAGER.Read_8Bits(FF_OR_CD_PITCH_ADDR);

    GET_SET[PID_YAW].kP = STORAGEMANAGER.Read_8Bits(KP_YAW_ADDR);
    GET_SET[PID_YAW].kI = STORAGEMANAGER.Read_8Bits(KI_YAW_ADDR);
    GET_SET[PID_YAW].kD = STORAGEMANAGER.Read_8Bits(KD_YAW_ADDR);
    GET_SET[PID_YAW].kFF = STORAGEMANAGER.Read_8Bits(FF_OR_CD_YAW_ADDR);

    GET_SET[PI_AUTO_LEVEL].kP = STORAGEMANAGER.Read_8Bits(KP_AUTOLEVEL_ADDR);
    GET_SET[PI_AUTO_LEVEL].kI = STORAGEMANAGER.Read_8Bits(KI_AUTOLEVEL_ADDR);

    GET_SET[PID_POSITION_Z].kP = STORAGEMANAGER.Read_8Bits(KP_POS_Z_ADDR);
    GET_SET[PID_POSITION_Z].kI = STORAGEMANAGER.Read_8Bits(KI_POS_Z_ADDR);
    GET_SET[PID_POSITION_Z].kD = STORAGEMANAGER.Read_8Bits(KD_POS_Z_ADDR);

    GET_SET[PID_VELOCITY_Z].kP = STORAGEMANAGER.Read_8Bits(KP_VEL_Z_ADDR);
    GET_SET[PID_VELOCITY_Z].kI = STORAGEMANAGER.Read_8Bits(KI_VEL_Z_ADDR);
    GET_SET[PID_VELOCITY_Z].kD = STORAGEMANAGER.Read_8Bits(KD_VEL_Z_ADDR);

    GET_SET[PID_GPS_POSITION].kP = STORAGEMANAGER.Read_8Bits(KP_GPSPOS_ADDR);
    GET_SET[PID_GPS_POSITION].kI = STORAGEMANAGER.Read_8Bits(KI_GPSPOS_ADDR);

    GET_SET[PID_GPS_POSITION_RATE].kP = STORAGEMANAGER.Read_8Bits(KP_POS_RATE_ADDR);
    GET_SET[PID_GPS_POSITION_RATE].kI = STORAGEMANAGER.Read_8Bits(KI_POS_RATE_ADDR);
    GET_SET[PID_GPS_POSITION_RATE].kD = STORAGEMANAGER.Read_8Bits(KD_POS_RATE_ADDR);

    GET_SET[PID_GPS_NAVIGATION_RATE].kP = STORAGEMANAGER.Read_8Bits(KP_NAV_RATE_ADDR);
    GET_SET[PID_GPS_NAVIGATION_RATE].kI = STORAGEMANAGER.Read_8Bits(KI_NAV_RATE_ADDR);
    GET_SET[PID_GPS_NAVIGATION_RATE].kD = STORAGEMANAGER.Read_8Bits(KD_NAV_RATE_ADDR);

    GET_SET[P_YAW_RATE].kP = STORAGEMANAGER.Read_8Bits(KP_HEADING_HOLD_ADDR);
    GET_SET[P_YAW_RATE_LIMIT].MaxValue = STORAGEMANAGER.Read_8Bits(HEADING_HOLD_RATE_LIMIT_ADDR);

    GET_SET[NAV_ROLL_BANK_MAX].MaxValue = STORAGEMANAGER.Read_8Bits(ROLL_BANK_ADDR);
    GET_SET[NAV_PITCH_BANK_MIN].MaxValue = STORAGEMANAGER.Read_8Bits(PITCH_BANK_MIN_ADDR);
    GET_SET[NAV_PITCH_BANK_MAX].MaxValue = STORAGEMANAGER.Read_8Bits(PITCH_BANK_MAX_ADDR);
    GET_SET[ATTACK_BANK_MAX].MaxValue = STORAGEMANAGER.Read_8Bits(ATTACK_BANK_ADDR);
    GET_SET[NAV_GPS_BANK_MAX].MaxValue = STORAGEMANAGER.Read_8Bits(GPS_BANK_ADDR);

    GET_SET[MAX_PITCH_LEVEL].MaxValue = STORAGEMANAGER.Read_8Bits(MAX_PITCH_LEVEL_ADDR);
    GET_SET[MAX_ROLL_LEVEL].MaxValue = STORAGEMANAGER.Read_8Bits(MAX_ROLL_LEVEL_ADDR);

    Load_GPS_Navigation_Params();
}

void DefaultForMultirotorPlatform(void)
{
    //PITCH
    STORAGEMANAGER.Write_8Bits(KP_PITCH_ADDR, 40);
    STORAGEMANAGER.Write_8Bits(KI_PITCH_ADDR, 30);
    STORAGEMANAGER.Write_8Bits(KD_PITCH_ADDR, 23);
    STORAGEMANAGER.Write_8Bits(FF_OR_CD_PITCH_ADDR, 60);

    //ROLL
    STORAGEMANAGER.Write_8Bits(KP_ROLL_ADDR, 40);
    STORAGEMANAGER.Write_8Bits(KI_ROLL_ADDR, 30);
    STORAGEMANAGER.Write_8Bits(KD_ROLL_ADDR, 23);
    STORAGEMANAGER.Write_8Bits(FF_OR_CD_ROLL_ADDR, 60);

    //YAW
    STORAGEMANAGER.Write_8Bits(KP_YAW_ADDR, 85);
    STORAGEMANAGER.Write_8Bits(KI_YAW_ADDR, 45);
    STORAGEMANAGER.Write_8Bits(KD_YAW_ADDR, 0);
    STORAGEMANAGER.Write_8Bits(FF_OR_CD_YAW_ADDR, 60);

    //AUTO-NÍVEL
    STORAGEMANAGER.Write_8Bits(KP_AUTOLEVEL_ADDR, 20);
    STORAGEMANAGER.Write_8Bits(KI_AUTOLEVEL_ADDR, 15);

    //POSIÇÃO Z
    STORAGEMANAGER.Write_8Bits(KP_POS_Z_ADDR, 3);
    STORAGEMANAGER.Write_8Bits(KI_POS_Z_ADDR, 5);
    STORAGEMANAGER.Write_8Bits(KD_POS_Z_ADDR, 10);

    //GPS-HOLD
    STORAGEMANAGER.Write_8Bits(KP_GPSPOS_ADDR, 100);
    STORAGEMANAGER.Write_8Bits(KI_GPSPOS_ADDR, 90);

    //RATE DO PID DA RETENÇÃO DE POSIÇÃO (GPS-HOLD)
    STORAGEMANAGER.Write_8Bits(KP_POS_RATE_ADDR, 70);
    STORAGEMANAGER.Write_8Bits(KI_POS_RATE_ADDR, 20);
    STORAGEMANAGER.Write_8Bits(KD_POS_RATE_ADDR, 20);

    //RATE DE NAVEGAÇÃO (RTH E MISSÃO)
    STORAGEMANAGER.Write_8Bits(KP_NAV_RATE_ADDR, 25);
    STORAGEMANAGER.Write_8Bits(KI_NAV_RATE_ADDR, 33);
    STORAGEMANAGER.Write_8Bits(KD_NAV_RATE_ADDR, 83);

    //ÂNGULOS DE NAVEGAÇÃO
    STORAGEMANAGER.Write_8Bits(ROLL_BANK_ADDR, 30);
    STORAGEMANAGER.Write_8Bits(PITCH_BANK_MIN_ADDR, 30);
    STORAGEMANAGER.Write_8Bits(PITCH_BANK_MAX_ADDR, 30);
    STORAGEMANAGER.Write_8Bits(ATTACK_BANK_ADDR, 40);
    STORAGEMANAGER.Write_8Bits(GPS_BANK_ADDR, 30);

    //RTH ALTITUDE
    STORAGEMANAGER.Write_8Bits(RTH_ALTITUDE_ADDR, 10);
}

void DefaultForAirPlanePlatform(void)
{
    //PITCH
    STORAGEMANAGER.Write_8Bits(KP_PITCH_ADDR, 5);
    STORAGEMANAGER.Write_8Bits(KI_PITCH_ADDR, 7);
    STORAGEMANAGER.Write_8Bits(KD_PITCH_ADDR, 0);
    STORAGEMANAGER.Write_8Bits(FF_OR_CD_PITCH_ADDR, 50);

    //ROLL
    STORAGEMANAGER.Write_8Bits(KP_ROLL_ADDR, 5);
    STORAGEMANAGER.Write_8Bits(KI_ROLL_ADDR, 7);
    STORAGEMANAGER.Write_8Bits(KD_ROLL_ADDR, 0);
    STORAGEMANAGER.Write_8Bits(FF_OR_CD_ROLL_ADDR, 50);

    //YAW
    STORAGEMANAGER.Write_8Bits(KP_YAW_ADDR, 6);
    STORAGEMANAGER.Write_8Bits(KI_YAW_ADDR, 10);
    STORAGEMANAGER.Write_8Bits(KD_YAW_ADDR, 0);
    STORAGEMANAGER.Write_8Bits(FF_OR_CD_YAW_ADDR, 60);

    //AUTO-NÍVEL
    STORAGEMANAGER.Write_8Bits(KP_AUTOLEVEL_ADDR, 20);
    STORAGEMANAGER.Write_8Bits(KI_AUTOLEVEL_ADDR, 5);

    //ALTITUDE-HOLD
    STORAGEMANAGER.Write_8Bits(KP_POS_Z_ADDR, 40);
    STORAGEMANAGER.Write_8Bits(KI_POS_Z_ADDR, 5);
    STORAGEMANAGER.Write_8Bits(KD_POS_Z_ADDR, 10);

    //AUTO-THROTTLE
    STORAGEMANAGER.Write_8Bits(KP_GPSPOS_ADDR, 150);
    STORAGEMANAGER.Write_8Bits(KI_GPSPOS_ADDR, 70);

    //RATE DO PID DA RETENÇÃO DE POSIÇÃO (CRUISE OU CIRCULOS)
    STORAGEMANAGER.Write_8Bits(KP_POS_RATE_ADDR, 75);
    STORAGEMANAGER.Write_8Bits(KI_POS_RATE_ADDR, 5);
    STORAGEMANAGER.Write_8Bits(KD_POS_RATE_ADDR, 8);

    //RATE DE NAVEGAÇÃO DO CONTROLE DO LEME (HEADING/YAW)
    STORAGEMANAGER.Write_8Bits(KP_NAV_RATE_ADDR, 30);
    STORAGEMANAGER.Write_8Bits(KI_NAV_RATE_ADDR, 2);
    STORAGEMANAGER.Write_8Bits(KD_NAV_RATE_ADDR, 0);

    //ÂNGULOS DE NAVEGAÇÃO
    STORAGEMANAGER.Write_8Bits(ROLL_BANK_ADDR, 45);
    STORAGEMANAGER.Write_8Bits(PITCH_BANK_MIN_ADDR, 20);
    STORAGEMANAGER.Write_8Bits(PITCH_BANK_MAX_ADDR, 25);
    STORAGEMANAGER.Write_8Bits(ATTACK_BANK_ADDR, 75);
    STORAGEMANAGER.Write_8Bits(GPS_BANK_ADDR, 30);

    //RTH ALTITUDE
    STORAGEMANAGER.Write_8Bits(RTH_ALTITUDE_ADDR, 40);
}

void DefaultForAllPlatforms(void)
{
    //VELOCIDADE Z
    STORAGEMANAGER.Write_8Bits(KP_VEL_Z_ADDR, 50);
    STORAGEMANAGER.Write_8Bits(KI_VEL_Z_ADDR, 20);
    STORAGEMANAGER.Write_8Bits(KD_VEL_Z_ADDR, 16);

    //HEADING-HOLD
    STORAGEMANAGER.Write_8Bits(KP_HEADING_HOLD_ADDR, 60);
    STORAGEMANAGER.Write_8Bits(HEADING_HOLD_RATE_LIMIT_ADDR, 90);
}

void UpdateValuesOfPID(void)
{
    if (GET_SET[PID_UPDATED].State)
    {
        return;
    }

    const uint8_t ActualFrameType = STORAGEMANAGER.Read_8Bits(FRAME_TYPE_ADDR);
    static uint8_t PreviousFrameType = ActualFrameType;

    //RECONFIGURA TODO O PID SE O FRAME SELECIONADO FOR DIFERENTE DO ANTERIOR
    //ISSO É NECESSARIO APENAS PARA A TROCA DO PERFIL DE MULTIROTOR PARA AERO E VICE-VERSA
    if (PreviousFrameType != ActualFrameType)
    {
        for (uint8_t IndexCount = 0; IndexCount < 5; IndexCount++)
        {
            if (ActualFrameType == QUAD_X ||
                ActualFrameType == HEXA_X ||
                ActualFrameType == HEXA_I ||
                ActualFrameType == ZMR_250 ||
                ActualFrameType == TBS)
            {
                DefaultForMultirotorPlatform();
            }
            else if (ActualFrameType == AIR_PLANE ||
                     ActualFrameType == FIXED_WING ||
                     ActualFrameType == AIR_PLANE_VTAIL)
            {
                DefaultForAirPlanePlatform();
            }

            DefaultForAllPlatforms();
        }
        PreviousFrameType = ActualFrameType;
    }

    Load_All_PID_Params();

    GET_SET[PID_UPDATED].State = true;
}